FROM node:20
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

COPY .env .env
RUN yarn prisma generate && yarn prisma migrate deploy

EXPOSE 3000

ENV NODE_ENV=development

CMD ["yarn", "dev"]
